Replace string with fixed size buffer
minipadKB/minipad-firmware pull request #17
Opened 2023-04-14 01:20 UTC by maidesu

All my homies use fixed length arrays

2023-04-23 10:41 UTC, minisbett commented
Very interesting approach, haven't seen the function readBytesUntil. Although could you elaborate on why you added a definition for the size of the input buffers?

2023-04-23 16:14 UTC, maidesu commented
Tl;dr from discord convo:

`readBytesUntil()` `char command[]` `char arg0[]` `char keyStr[]` `char setting[]`
all depend on the length of `char buff[]` as a "worst case" size - their contents will always be
less than or equal to the buffer itself.

2023-04-26 16:18 UTC, minisbett commented
Is this still a draft?

2023-04-26 16:26 UTC, maidesu commented
No more changes planned here until testing

2023-04-27 06:38 UTC, minisbett requested changes
Requested some changes and left some questions.

2023-04-27 06:38 UTC, minisbett commented on include/definitions.hpp
> +#define INPUT_BUFF_SIZE 64
Could you change this to 256?

2023-04-27 06:38 UTC, minisbett commented on src/handlers/serial_handler.cpp
> +void SerialHandler::handleSerialInput(char *buff)
Could you rename this to something like "input"? I think that name is a better indicator for it's purpose than "buff"

2023-04-27 06:38 UTC, minisbett commented on src/main.cpp
> +    while (Serial.available() > 0)
What's this > 0 check for?

2023-04-27 12:34 UTC, maidesu commented on src/main.cpp
> +    while (Serial.available() > 0)
> Returns
> The number of bytes available to read.

The return type int from the function `Serial.available()` could technically make the expression
`( Serial.available() )` true for negative integers while `( Serial.available() > 0 )` is obviously only true for
positive integers.

See [Serial.available()](https://reference.arduino.cc/reference/en/language/functions/communication/serial/available/)

2023-04-28 07:26 UTC, minisbett commented on src/main.cpp
> +    while (Serial.available() > 0)
hmm I get the idea

2023-05-10 07:46 UTC, minisbett commented
Could you solve merge conflicts and check whether recently added code needs to be adjusted as well?

2023-05-14 18:56 UTC, minisbett requested changes
https://github.com/minipadKB/minipad-firmware/pull/17#issuecomment-1541511790

2023-08-12 11:04 UTC, minisbett commented
Replaced by #42

2023-08-12 11:04 UTC, closed without merging